# Generated by Django 6.0.4 on 2026-04-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('cus_id', models.IntegerField()),
                ('schedule_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Booking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('tour_id', models.AutoField(primary_key=True, serialize=False)),
                ('tour_name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'tourpackage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewCustomer',
            fields=[
                ('CusID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Cusname', models.CharField(max_length=50)),
                ('RegisYear', models.IntegerField()),
                ('EmpID', models.CharField(max_length=10)),
                ('EMPName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'viewCustomer',
                'managed': False,
            },
        ),
    ]
